config/routes.rb
Blog::Application.routes.draw do
  require 'api_constraints'

  match '/auth/:provider/callback' => 'authentications#create'
  
  devise_for :admins, :controllers => { :sessions => 'admin/sessions', :registrations => 'admin/registrations' }

  namespace :admin do
      resources :users
      resources :celebrations

      authenticated :admin do
        root :to => 'admins#dashboard'
      end

      devise_scope :admin do
        root :to => 'sessions#new'
      end
  end

  devise_for :users, :controllers => {:registrations => 'registrations'}

  resources :posts do
    resources :comments
  end

  namespace :api, defaults: {format: 'json'} do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: :true) do
      get 'celebrations/(:til)' => 'celebrations#index'
      get 'facebook/upcoming_birthdays/(:til)' => 'facebook#upcoming_birthdays'
      get 'facebook/photos_together/(:til)' => 'facebook#photos_together' 
    end
  end

  get '/invite' => 'home#invite'

  root :to => "home#index"

end

app/models/celebration.rb
class Celebration < ActiveRecord::Base
  attr_accessible :celebrated_on, :country, :message, :name

  validates :name, :presence => true
  validates :country, :presence => true
  validates :message, :presence => true
  validate  :future_date

  def future_date
  	if celebrated_on.past?
  	errors.add(:celebrated_on, "Can't be in the past") 
  	end
  end

  def self.upcoming(til = 1.week.from_now)
  	where("celebrated_on >= ? AND celebrated_on <= ?", Time.now, til).order("celebrated_on ASC")
  end
end

app/controllers/admin/celebrations_controller.rb
class Admin::CelebrationsController < Admin::BaseController
  # GET /celebrations
  # GET /celebrations.json
  def index
    #@celebrations = Celebration.where("celebrated_on >= ?", Time.now).order("celebrated_on ASC").page(params[:page])

    @search = Celebration.search(params[:q])
    @celebrations = @search.result.order("celebrated_on ASC").page(params[:page]).per(3)
    @search.build_condition

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @celebrations }
    end
  end

  # GET /celebrations/1
  # GET /celebrations/1.json
  def show
    @celebration = Celebration.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @celebration }
    end
  end

  # GET /celebrations/new
  # GET /celebrations/new.json
  def new
    @celebration = Celebration.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @celebration }
    end
  end

  # GET /celebrations/1/edit
  def edit
    @celebration = Celebration.find(params[:id])
  end

  # POST /celebrations
  # POST /celebrations.json
  def create
    @celebration = Celebration.new(params[:celebration])

    respond_to do |format|
      if @celebration.save
        format.html { redirect_to @celebration, notice: 'Celebration was successfully created.' }
        format.json { render json: @celebration, status: :created, location: @celebration }
      else
        format.html { render action: "new" }
        format.json { render json: @celebration.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /celebrations/1
  # PUT /celebrations/1.json
  def update
    @celebration = Celebration.find(params[:id])

    respond_to do |format|
      if @celebration.update_attributes(params[:celebration])
        format.html { redirect_to @celebration, notice: 'Celebration was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @celebration.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /celebrations/1
  # DELETE /celebrations/1.json
  def destroy
    @celebration = Celebration.find(params[:id])
    @celebration.destroy

    respond_to do |format|
      format.html { redirect_to celebrations_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/api/v1/celebrations_controller.rb
module Api
  module V1
    class CelebrationsController < ApplicationController
      respond_to :json

      def index
      	til = params[:til] || 1.week.from_now
      	respond_with Celebration.upcoming(Time.at til.to_i)
      end

    end
  end
end

app/controllers/celebrations_controller.rb
class CelebrationsController < ApplicationController
  # GET /celebrations
  # GET /celebrations.json
  def index
    #@celebrations = Celebration.where("celebrated_on >= ?", Time.now).order("celebrated_on ASC").page(params[:page])

    @search = Celebration.search(params[:q])
    @celebrations = @search.result.order("celebrated_on ASC").page(params[:page]).per(3)
    @search.build_condition

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @celebrations }
    end
  end

  # GET /celebrations/1
  # GET /celebrations/1.json
  def show
    @celebration = Celebration.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @celebration }
    end
  end

  # GET /celebrations/new
  # GET /celebrations/new.json
  def new
    @celebration = Celebration.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @celebration }
    end
  end

  # GET /celebrations/1/edit
  def edit
    @celebration = Celebration.find(params[:id])
  end

  # POST /celebrations
  # POST /celebrations.json
  def create
    @celebration = Celebration.new(params[:celebration])

    respond_to do |format|
      if @celebration.save
        format.html { redirect_to @celebration, notice: 'Celebration was successfully created.' }
        format.json { render json: @celebration, status: :created, location: @celebration }
      else
        format.html { render action: "new" }
        format.json { render json: @celebration.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /celebrations/1
  # PUT /celebrations/1.json
  def update
    @celebration = Celebration.find(params[:id])

    respond_to do |format|
      if @celebration.update_attributes(params[:celebration])
        format.html { redirect_to @celebration, notice: 'Celebration was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @celebration.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /celebrations/1
  # DELETE /celebrations/1.json
  def destroy
    @celebration = Celebration.find(params[:id])
    @celebration.destroy

    respond_to do |format|
      format.html { redirect_to celebrations_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/celebrations_helper.rb
module CelebrationsHelper
end

app/views/admin/celebrations/_condition_fields.html.erb
<div class="field">
	<%= f.attribute_fields do |a| %>
	  <% a.attribute_select associations: [:category] %>
	<% end %>
	<%= f.predicate_select %>
	<%= f.value_fields do |v| %>
	  <%= v.text_field :value %>
	<% end %>
	<%= link_to "remove", '#', class: "remove_fields btn" %>
</div> 

app/views/admin/celebrations/_form.html.erb
<%= form_for @celebration, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :celebrated_on, :class => 'control-label' %>
    <div class="controls">
      <%= f.date_select :celebrated_on, :class => 'date_select' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :message, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :message, :class => 'text_area' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :country, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :country, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                admin_celebrations_path, :class => 'btn' %>
  </div>
<% end %>

app/views/admin/celebrations/edit.html.erb
<%- model_class = Celebration -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/admin/celebrations/index.html.erb
<%- model_class = Celebration -%>

<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>

<%= search_form_for @search do |s| %>
  <%= s.condition_fields do |c| %>
    <%= render "condition_fields", f: c%>
  <% end %>
  <p><%= link_to_add_fields "Add Conditions", s, :condition %>
  <div class="actions"><%= s.submit "Search" %></div>
<% end %>

<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= sort_link(@search, :name, model_class.human_attribute_name(:name)) %></th>
      <th><%= sort_link(@search, :celebrated_on, model_class.human_attribute_name(:celebrated_on)) %></th>
      <th><%= model_class.human_attribute_name(:message) %></th>
      <th><%= sort_link(@search, :country, model_class.human_attribute_name(:country)) %></th>
      <th><%= sort_link(@search, :created_at, model_class.human_attribute_name(:created_at)) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @celebrations.each do |celebration| %>
      <tr>
        <td><%= link_to celebration.id, admin_celebration_path(celebration) %></td>
        <td><%= celebration.name %></td>
        <td><%= celebration.celebrated_on %></td>
        <td><%= celebration.message %></td>
        <td><%= celebration.country %></td>
        <td><%=l celebration.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_admin_celebration_path(celebration), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      admin_celebration_path(celebration),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @celebrations %>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_admin_celebration_path,
            :class => 'btn btn-primary' %>

app/views/admin/celebrations/new.html.erb
<%- model_class = Celebration -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/admin/celebrations/show.html.erb
<%- model_class = Celebration -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @celebration.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:celebrated_on) %>:</strong></dt>
  <dd><%= @celebration.celebrated_on %></dd>
  <dt><strong><%= model_class.human_attribute_name(:message) %>:</strong></dt>
  <dd><%= @celebration.message %></dd>
  <dt><strong><%= model_class.human_attribute_name(:country) %>:</strong></dt>
  <dd><%= @celebration.country %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              admin_celebrations_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_admin_celebration_path(@celebration), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              admin_celebration_path(@celebration),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>