config/routes.rb
Blog::Application.routes.draw do
  require 'api_constraints'

  match '/auth/:provider/callback' => 'authentications#create'
  
  devise_for :admins, :controllers => { :sessions => 'admin/sessions', :registrations => 'admin/registrations' }

  namespace :admin do
      resources :users
      resources :celebrations

      authenticated :admin do
        root :to => 'admins#dashboard'
      end

      devise_scope :admin do
        root :to => 'sessions#new'
      end
  end

  devise_for :users, :controllers => {:registrations => 'registrations'}

  resources :posts do
    resources :comments
  end

  namespace :api, defaults: {format: 'json'} do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: :true) do
      get 'celebrations/(:til)' => 'celebrations#index'
      get 'facebook/upcoming_birthdays/(:til)' => 'facebook#upcoming_birthdays'
      get 'facebook/photos_together/(:til)' => 'facebook#photos_together' 
    end
  end

  get '/invite' => 'home#invite'

  root :to => "home#index"

end

app/views/layouts/_menu.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <a class="brand" href="/">Some Blog</a>
      <div class="nav-collapse">
        <ul class="nav">
          <li><%= link_to "Browse Posts", posts_path %></li>

          <% if admin_signed_in? %>
            <li><%= link_to "Celebrations", admin_celebrations_path %></li>
          <% end %>

          <li><%= link_to "Invite Friends", "/invite" %></li>
          <% if admin_signed_in? %>
            <li><%= link_to "Browse Users", admin_users_path %></li>
          <% end %>
          <li><%= render 'devise/menu/registration_items' %></li>
          <li><%= render 'devise/menu/login_items' %></li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>

<body>

<%= render "layouts/menu" %>

<div class="container">

  <% if notice %>
    <p class="notice"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p class="alert"><%= alert %></p>
  <% end %>

  <div class="row">
    <div class="span9"><%= yield %></div>
      <div class="span3">
        <h2> About Us </h2>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. </p>
      </div>
    </div>
  </div>
</div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>

<body>


<div id="fb-root"></div>
<script>

  window.fbAsyncInit = function() {
    FB.init({
      appId      : '269346943176907', // App ID
      channelUrl :  '//'+window.location.hostname+'/channel.html', // Channel File
      status     : true, // check login status
      cookie     : true, // enable cookies to allow the server to access the session
      xfbml      : true  // parse XFBML
    });
    FB.Canvas.setAutoGrow();

    <% if !user_signed_in? and !admin_signed_in? %>
    
    FB.getLoginStatus(function(response) {

      if (response.status === 'not_authorized' || response.status === 'connected') {
        top.location.href = "auth/facebook"
        
      } 
    });

    <% end %>
  };

  // Load the SDK Asynchronously
  (function(d){
     var js, id = 'facebook-jssdk', ref = d.getElementsByTagName('script')[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement('script'); js.id = id; js.async = true;
     js.src = "//connect.facebook.net/en_US/all.js";
     ref.parentNode.insertBefore(js, ref);
   }(document));
</script>

<%= render "layouts/menu" %>

<div class="container">

  <% if notice %>
    <p class="notice"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p class="alert"><%= alert %></p>
  <% end %>

  <div class="row">
    <div class="span9"><%= yield %></div>
      <div class="span3">
        <h2> About Us </h2>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. </p>
      </div>
    </div>
  </div>
</div>
</body>
</html>